import { Briefing } from '@/types/briefing'
import { 
  TrendingUp, 
  AlertTriangle, 
  Users, 
  CheckCircle,
  Building2,
  Calendar
} from 'lucide-react'

interface BriefingOutputProps {
  briefing: Briefing
}

const sections = [
  {
    key: 'keyNumbers' as const,
    icon: TrendingUp,
    color: 'blue',
    bg: 'bg-blue-50',
    border: 'border-blue-200',
    iconColor: 'text-blue-600',
    titleColor: 'text-blue-800',
  },
  {
    key: 'alerts' as const,
    icon: AlertTriangle,
    color: 'amber',
    bg: 'bg-amber-50',
    border: 'border-amber-200',
    iconColor: 'text-amber-600',
    titleColor: 'text-amber-800',
  },
  {
    key: 'staffing' as const,
    icon: Users,
    color: 'purple',
    bg: 'bg-purple-50',
    border: 'border-purple-200',
    iconColor: 'text-purple-600',
    titleColor: 'text-purple-800',
  },
  {
    key: 'recommendedActions' as const,
    icon: CheckCircle,
    color: 'green',
    bg: 'bg-green-50',
    border: 'border-green-200',
    iconColor: 'text-green-600',
    titleColor: 'text-green-800',
  },
]

export default function BriefingOutput({ briefing }: BriefingOutputProps) {
  return (
    <div className="flex flex-col gap-6">
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-900 to-blue-700 rounded-xl p-6 text-white">
        <div className="flex items-center gap-2 mb-1">
          <Building2 className="w-5 h-5 opacity-80" />
          <span className="text-blue-200 text-sm font-medium uppercase tracking-wide">
            Daily Operations Briefing
          </span>
        </div>
        <h1 className="text-2xl font-bold">{briefing.hotelName}</h1>
        <div className="flex items-center gap-2 mt-2">
          <Calendar className="w-4 h-4 opacity-70" />
          <span className="text-blue-200 text-sm">{briefing.date}</span>
        </div>
      </div>

      {/* Sections */}
      {sections.map(({ key, icon: Icon, bg, border, iconColor, titleColor }) => (
        <div
          key={key}
          className={`${bg} ${border} border rounded-xl p-5`}
        >
          <div className="flex items-center gap-2 mb-3">
            <Icon className={`w-5 h-5 ${iconColor}`} />
            <h3 className={`font-semibold ${titleColor}`}>
              {briefing[key].title}
            </h3>
          </div>
          <ul className="flex flex-col gap-2">
            {briefing[key].items.map((item, index) => (
              <li key={index} className="flex items-start gap-2">
                <span className={`${iconColor} mt-1 text-xs`}>▸</span>
                <span className="text-gray-700 text-sm leading-relaxed">{item}</span>
              </li>
            ))}
          </ul>
        </div>
      ))}

      {/* Footer */}
      <p className="text-xs text-gray-400 text-center pb-2">
        Generated by Zenith Ops AI · {new Date().toLocaleTimeString('en-AU')}
      </p>
    </div>
  )
}